//
//  HomeModels.swift
//  OneTwoThreeApp
//
//  Created by Orawan Manasombun on 23/6/21.
//  Copyright (c) 2021 2C2P. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {
    
    // MARK: Use cases
    
    enum GetProducts {
        struct Request
        {
        }
        struct Response
        {
            let products: [Product]
        }
        struct ViewModel
        {
            let products: [Product]
        }
    }
    
    enum Payment {
        struct Request
        {
            let product: Product
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    
    enum Custom {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }

}
