//
//  HomeRouter.swift
//  OneTwoThreeApp
//
//  Created by Orawan Manasombun on 23/6/21.
//  Copyright (c) 2021 2C2P. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic {
    func routeToPayment(segue: UIStoryboardSegue?)
}

protocol HomeDataPassing {
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing {
    
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?
    
    // MARK: Routing
    
    func routeToPayment(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! PaymentViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToPayment(source: dataStore!, destination: &destinationDS)
        }
    }
    
    // MARK: - Passing data
    
    func passDataToPayment(source: HomeDataStore, destination: inout PaymentDataStore) {
        destination.product = source.product
    }
}
