//
//  HomeWorker.swift
//  OneTwoThreeApp
//
//  Created by Orawan Manasombun on 23/6/21.
//  Copyright (c) 2021 2C2P. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeWorker {
    
    func doFetchProducts(completion: @escaping GenericCompletionBlock<[Product]>) {
        let products: [Product] = [
            Product(
                name: "Omega",
                desc: "Founded in a small Swiss village under Louis Brandt & Fil.",
                amount: "1",
                image: #imageLiteral(resourceName: "omega")
            ),
            Product(
                name: "Laurent Ferrier",
                desc: "The designs are precise, simple, and unfussy.",
                amount: "1.5",
                image: #imageLiteral(resourceName: "laurent_ferrier")
            ),
            Product(
                name: "A. Lange and Söhne",
                desc: "German luxury watch founded in 1845.",
                amount: "10.00",
                image: #imageLiteral(resourceName: "lange_sohne")
            )
        ]
        completion(products)
    }
}
