//
//  HomeInteractor.swift
//  OneTwoThreeApp
//
//  Created by Orawan Manasombun on 23/6/21.
//  Copyright (c) 2021 2C2P. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic {
    func doGetProducts(request: Home.GetProducts.Request)
    func doNavigateToPayment(request: Home.Payment.Request)
    func doNavigateToCustom(request: Home.Custom.Request)
}

protocol HomeDataStore {
    var product: Product? { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore {
    
    var presenter: HomePresentationLogic?
    var worker: HomeWorker?

    var product: Product?
    
    // MARK: - Get Products
    
    func doGetProducts(request: Home.GetProducts.Request) {
        worker = HomeWorker()
        worker?.doFetchProducts(completion: { products in
            let response = Home.GetProducts.Response(products: products)
            self.presenter?.presentProducts(response: response)
        })
    }
    
    // MARK: - Navigate to Payment
    
    func doNavigateToPayment(request: Home.Payment.Request) {
        product = request.product
        
        let response = Home.Payment.Response()
        presenter?.presentPayment(response: response)
    }
    
    // MARK: - Navigate to Custom
    
    func doNavigateToCustom(request: Home.Custom.Request) {
        let response = Home.Custom.Response()
        presenter?.presentCustom(response: response)
    }
    
}
