//
//  CustomWorker.swift
//  OneTwoThreeApp
//
//  Created by Orawan Manasombun on 28/6/21.
//  Copyright (c) 2021 2C2P. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum InputType: Equatable, CaseIterable {
    case merchantID
    case redirectURL
    case notificationURL
    case merchantData
    
    case merchantReference
    case perferredAgent
    case productDesc
    case paymentInfo
    case amount
    case currencyCode
    case paymentExpiry
    case userDefined1
    case userDefined2
    case userDefined3
    case userDefined4
    case userDefined5
    
    case buyerEmail
    case buyerMobile
    case buyerLanguage
    case buyerOS
    case buyerNotify
    case buyerTitle
    case buyerFirstName
    case buyerLastName
    
    var title: String {
        switch self {
        case .merchantID:           return "Merchant ID"
        case .redirectURL:          return "Redirect URL"
        case .notificationURL:      return "Notification URL"
        case .merchantData:         return "Merchant Data"
            
        case .merchantReference:    return "Merchant Reference"
        case .perferredAgent:       return "Preferred Agent (BAY, BBL, SCB, etc.)"
        case .productDesc:          return "Product Description"
        case .paymentInfo:          return "Payment Info"
        case .amount:               return "Amount"
        case .currencyCode:         return "Currency Code (THB, USD, etc.)"
        case .paymentExpiry:        return "Payment Expiry (\(Constants.dateFormat))"
        case .userDefined1:         return "User Defined 1"
        case .userDefined2:         return "User Defined 2"
        case .userDefined3:         return "User Defined 3"
        case .userDefined4:         return "User Defined 4"
        case .userDefined5:         return "User Defined 5"
            
        case .buyerEmail:           return "Buyer Email"
        case .buyerMobile:          return "Buyer Mobile"
        case .buyerLanguage:        return "Buyer Language (EN, TH, etc.)"
        case .buyerOS:              return "Buyer OS (0 = iOS / 1 = Android)"
        case .buyerNotify:          return "Notify Buyer (true / false)"
        case .buyerTitle:           return "Buyer Title"
        case .buyerFirstName:       return "Buyer Name"
        case .buyerLastName:        return "Buyer Surname"
        }
    }
    
    var placeholder: String {
        switch self {
        case .merchantID:           return "Enter Merchant ID"
        case .redirectURL:          return "Enter Redirect URL"
        case .notificationURL:      return "Enter Notification URL"
        case .merchantData:         return "title:value,title:value"
        
        case .merchantReference:    return "Enter Merchant Reference"
        case .perferredAgent:       return "Enter Preferred Agent"
        case .productDesc:          return "Enter Product Description"
        case .paymentInfo:          return "Enter Payment Info"
        case .amount:               return "Enter Amount"
        case .currencyCode:         return "Enter Currency Code"
        case .paymentExpiry:        return "Enter Payment Expiry"
        case .userDefined1:         return "User Defined 1"
        case .userDefined2:         return "User Defined 2"
        case .userDefined3:         return "User Defined 3"
        case .userDefined4:         return "User Defined 4"
        case .userDefined5:         return "User Defined 5"
            
        case .buyerEmail:           return "Enter Buyer Email"
        case .buyerMobile:          return "Enter Buyer Mobile"
        case .buyerLanguage:        return "Enter Buyer Language"
        case .buyerOS:              return "Enter Buyer OS"
        case .buyerNotify:          return "Enter Notify Buyer"
        case .buyerTitle:           return "Enter Buyer Title"
        case .buyerFirstName:       return "Enter Buyer Name"
        case .buyerLastName:        return "Enter Buyer Surname"
        }
    }
    
    var isRequired: String {
        switch self {
        case .merchantID, .redirectURL, .merchantReference, .perferredAgent, .amount, .currencyCode, .productDesc, .buyerEmail, .buyerMobile, .buyerLanguage, .buyerOS, .buyerNotify:
            return "*"
            
        default:
            return ""
        }

    }
}


class CustomWorker {
    
    func doFetchInputTypes(completion: @escaping GenericCompletionBlock<[InputType]>) {
        completion(InputType.allCases)
    }
}
