//
//  CustomModels.swift
//  OneTwoThreeApp
//
//  Created by Orawan Manasombun on 28/6/21.
//  Copyright (c) 2021 2C2P. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import OneTwoThreeSDK

enum Custom {
    
    // MARK: Use cases
    
    enum Initial
    {
        struct Request
        {
        }
        struct Response
        {
            let types: [InputType]
        }
        struct ViewModel
        {
            let types: [InputType]
        }
    }
    
    enum StartDeeplink
    {
        struct Request
        {
            let merchant: Merchant
            let transaction: Transaction
            let buyer: Buyer
        }
        struct Response
        {
            let response: StartDeeplinkResponse?
        }
        struct ViewModel
        {
            let response: StartDeeplinkResponse?
        }
    }

    enum Error {
        struct Request
        {
        }
        struct Response
        {
            let error: ErrorEvent?
        }
        struct ViewModel
        {
            let error: ErrorEvent?
        }
    }}
