//
//  CustomPresenter.swift
//  OneTwoThreeApp
//
//  Created by Orawan Manasombun on 28/6/21.
//  Copyright (c) 2021 2C2P. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CustomPresentationLogic {
    func presentInitial(response: Custom.Initial.Response)
    func presentDeeplink(response: Custom.StartDeeplink.Response)
    func presentError(response: Custom.Error.Response)
}

class CustomPresenter: CustomPresentationLogic {
    
    weak var viewController: CustomDisplayLogic?
    
    // MARK: - Initial
    
    func presentInitial(response: Custom.Initial.Response) {
        let viewModel = Custom.Initial.ViewModel(types: response.types)
        viewController?.displayInitial(viewModel: viewModel)
    }
    
    // MARK: - Deeplink
    
    func presentDeeplink(response: Custom.StartDeeplink.Response) {
        let viewModel = Custom.StartDeeplink.ViewModel(response: response.response)
        viewController?.displayDeeplink(viewModel: viewModel)
    }
    
    // MARK: - Error
    
    func presentError(response: Custom.Error.Response) {
        let viewModel = Custom.Error.ViewModel(error: response.error)
        viewController?.displayError(viewModel: viewModel)
    }
}
