//
//  PaymentPresenter.swift
//  OneTwoThreeApp
//
//  Created by Orawan Manasombun on 24/6/21.
//  Copyright (c) 2021 2C2P. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PaymentPresentationLogic {
    func presentInitial(response: Payment.Initial.Response)
    func presentDeeplink(response: Payment.StartDeeplink.Response)
    func presentError(response: Payment.Error.Response)
}

class PaymentPresenter: PaymentPresentationLogic {
    
    weak var viewController: PaymentDisplayLogic?
    
    // MARK: - Initial
    
    func presentInitial(response: Payment.Initial.Response) {
        let viewModel = Payment.Initial.ViewModel(product: response.product)
        viewController?.displayInitial(viewModel: viewModel)
    }
    
    // MARK: - Deeplink
    
    func presentDeeplink(response: Payment.StartDeeplink.Response) {
        let viewModel = Payment.StartDeeplink.ViewModel(response: response.response)
        viewController?.displayDeeplink(viewModel: viewModel)
    }
    
    // MARK: - Error
    
    func presentError(response: Payment.Error.Response) {
        let viewModel = Payment.Error.ViewModel(error: response.error)
        viewController?.displayError(viewModel: viewModel)
    }
    
}
