//
//  PaymentModels.swift
//  OneTwoThreeApp
//
//  Created by Orawan Manasombun on 24/6/21.
//  Copyright (c) 2021 2C2P. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import OneTwoThreeSDK

enum PaymentMethod: Int {
    case scb = 0
    case bay = 1
    case bbl = 2
    
    // NOTE: Refer to Merchant Integration Document.
    //       Appendix B. Available Agents and Channels by Country.
    var abbreviation: String {
        switch self {
        case .scb:      return "SCB"
        case .bay:      return "BAY"
        case .bbl:      return "BBL"
        }
    }
    
    var bankName: String {
        switch self {
        case .scb:      return "SCB"
        case .bay:      return "Krungsri"
        case .bbl:      return "Bualuang"
        }
    }
}

enum Payment {
    
    // MARK: Use cases
    
    enum Initial {
        struct Request
        {
        }
        struct Response
        {
            let product: Product?
        }
        struct ViewModel
        {
            let product: Product?
        }
    }
    
    enum StartDeeplink {
        struct Request
        {
            let paymentMethod: PaymentMethod?
        }
        struct Response
        {
            let response: StartDeeplinkResponse?
        }
        struct ViewModel
        {
            let response: StartDeeplinkResponse?
        }
    }
    
    enum Error {
        struct Request
        {
        }
        struct Response
        {
            let error: ErrorEvent?
        }
        struct ViewModel
        {
            let error: ErrorEvent?
        }
    }
}
